services:
  crm-service:
    build: .
    container_name: crm-service
    ports:
      - "8000:8000"
    environment:
      - AWS_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    extra_hosts:
      - "host.docker.internal:host-gateway"
